"""
File: scripts/lint/check_rules_hygiene.py
Purpose: Always-loaded rule-file hygiene lint — byte budgets on CLAUDE.md +
    .claude/rules/*, and a row-length cap on the calibration matrix.
Category: Tooling / lint
Scope: Template v2.6.1

Description:
    Claude Code auto-loads CLAUDE.md + every .claude/rules/*.md into EVERY
    session's context. Without a mechanical guard these files accrete
    per-phase evidence until they eat a double-digit percentage of the
    context window at session start.

    In the source project this happened TWICE to the same table (~2000+
    chars/cell, 47% of the file) because the only guard was an advisory
    prose note — each phase closeout copied the previous bloated cell as
    its template and nothing ever failed. This lint is that missing guard.

    Check A — matrix row cap: every table row in the calibration matrix
        (any line starting "|", outside code fences, separator rows aside)
        must be <= MATRIX_ROW_MAX chars. Full narration belongs in
        calibration-log.md, never in the matrix cell.
    Check B — size budgets: each always-loaded file must stay under its
        byte budget. Exceeding a budget means evidence/history is
        accumulating in a rules file — move it to an on-demand doc.

    A budgeted file that is MISSING is also a violation: if the file was
    intentionally moved/renamed, update SIZE_BUDGETS below consciously.

Key Components:
    - Violation: NamedTuple (file, kind, detail). NamedTuple, NOT dataclass:
      tests may load this script via importlib file-path, where
      dataclass + future-annotations breaks.
    - find_violations(repo_root): pure function; unit-testable via tmp_path.
    - main(): CLI wrapper; exit 0 = clean, 1 = violations found.

Usage:
    python scripts/lint/check_rules_hygiene.py [--root <repo_root>]

Created: 2026-08-07
Last Modified: 2026-08-07

Modification History (newest-first):
    - 2026-08-07: Initial creation from claude-code-dev-template v2.6.1

Related:
    - .claude/rules/README.md — the always-loaded vs on-demand split
    - .claude/rules/task-workflow.md §Phase Closeout
    - docs/01-planning/CALIBRATION-MATRIX.md
"""

import argparse
import sys
from pathlib import Path
from typing import NamedTuple

MATRIX_FILE = "docs/01-planning/CALIBRATION-MATRIX.md"
MATRIX_ROW_MAX = 400

# Byte budgets. Set these to (current size + ~25-40% headroom) once your
# project's rule files have settled.
#
# Raising a budget is a CONSCIOUS decision: justify it in the commit that
# raises it. Usually the right fix is moving content on-demand instead —
# a rules file that keeps growing is accumulating evidence/history that
# belongs in docs/rules-on-demand/ or the calibration log.
# Baseline = size as generated by the template (python-fastapi-react profile,
# the most verbose one) + ~35% headroom. Re-baseline once your project's rules
# have settled — but ONLY upward when the growth is genuinely new RULE content,
# never accumulated evidence/history.
# v2.5.0 RE-BASELINE. Several notes below had gone stale (CLAUDE.md was noted
# as "~15,000 generated" while actually generating ~19,400; rules/README was
# noted as "~5,600" while actually ~9,200). A budget whose baseline comment is
# wrong stops being a guard and becomes a tripwire: three files sat at 97-99%,
# so the NEXT edit of any kind failed -- including the ones GETTING-STARTED
# explicitly tells you to make (filling in §Core Vision / §Architecture).
#
# Re-baselined to (measured with the most verbose profile) + ~20-35% headroom.
# The headroom exists for the PROJECT'S OWN rule content, not for phase records.
# If you are raising one of these to fit accumulated evidence/history, the raise
# is wrong -- move the content to docs/rules-on-demand/ or the calibration log.
#
# PROJECT DEVIATION (2026-08-07, isms-governance-portal): CLAUDE.md raised
# 24,000 -> 30,000. This project's always-loaded content carries two blocks a
# generic project does not: 9 non-negotiable security/compliance guardrails and
# 15 confirmed parameters that must not be re-litigated. Both are stable domain
# constraints, not accumulated evidence/history -- i.e. exactly the "PROJECT'S
# OWN rule content" the note above says the headroom is for. Traditional Chinese
# also costs 3 bytes/char in UTF-8, so a byte budget is ~3x tighter here than for
# an English project of the same reading length.
#
# The accretion guard still bites: at 27,644 actual the file can only grow ~2.4KB
# before failing, which is well under one phase-record's worth of creep.
# If a future raise is needed to fit phase records, that raise is wrong -- move
# them to W{NN}-*/retrospective.md or memory/ instead.
SIZE_BUDGETS: dict[str, int] = {
    "CLAUDE.md": 30_000,  # ~19,400 generated + ~8,200 project guardrails/parameters
    ".claude/rules/task-workflow.md": 32_000,  # ~23,600 generated
    ".claude/rules/verification-discipline.md": 11_000,  # ~8,900 generated
    ".claude/rules/file-header-convention.md": 13_000,  # ~9,100 generated
    ".claude/rules/anti-patterns-checklist.md": 10_000,  # ~6,800 generated
    ".claude/rules/tool-discipline.md": 4_000,  # ~2,500 generated
    ".claude/rules/README.md": 11_500,  # ~9,200 generated
    MATRIX_FILE: 60_000,  # on-demand, but rows accrete one per phase
}

# Total always-loaded budget ≈ 106 KB; actually generated ≈ 80 KB. For
# reference: the source project's equivalent files reached ~130 KB before the
# cleanup that produced these rules — roughly 9-12% of a session's context
# window at startup.
#
# Re-measure with:
#   python - <<'EOF'
#   from pathlib import Path
#   from scripts.lint.check_rules_hygiene import SIZE_BUDGETS
#   for rel, b in SIZE_BUDGETS.items():
#       p = Path(rel)
#       print(f"{rel:48} {p.stat().st_size if p.is_file() else 0:6} / {b:6}")
#   EOF


class Violation(NamedTuple):
    file: str
    kind: str  # "missing" | "over_budget" | "matrix_row"
    detail: str


def find_violations(repo_root: Path) -> list[Violation]:
    """Return all hygiene violations under repo_root (empty list = clean)."""
    violations: list[Violation] = []

    for rel, budget in SIZE_BUDGETS.items():
        path = repo_root / rel
        if not path.is_file():
            violations.append(
                Violation(
                    rel,
                    "missing",
                    "budgeted always-loaded file not found -- if moved/renamed, "
                    "update SIZE_BUDGETS in check_rules_hygiene.py",
                )
            )
            continue
        size = path.stat().st_size
        if size > budget:
            violations.append(
                Violation(
                    rel,
                    "over_budget",
                    f"{size:,} bytes > budget {budget:,} -- move evidence/history "
                    f"to an on-demand doc (docs/rules-on-demand/ or calibration-log.md)",
                )
            )

    matrix = repo_root / MATRIX_FILE
    if matrix.is_file():
        in_fence = False
        for lineno, line in enumerate(
            matrix.read_text(encoding="utf-8").splitlines(), start=1
        ):
            stripped = line.strip()
            if stripped.startswith("```"):
                in_fence = not in_fence
                continue
            # Any table row counts. An earlier version matched only rows whose
            # first cell was backticked ("| `") — a row written without them
            # slipped past silently while the success message still claimed the
            # cap was enforced. Found by a negative test; do not narrow this again.
            if in_fence or not stripped.startswith("|"):
                continue
            if set(stripped) <= set("|-: "):  # separator row
                continue
            if len(line) > MATRIX_ROW_MAX:
                violations.append(
                    Violation(
                        MATRIX_FILE,
                        "matrix_row",
                        f"L{lineno} row is {len(line)} chars > {MATRIX_ROW_MAX} -- "
                        f"keep verdict + ratio/band + rollback trigger + pointer; "
                        f"full narration goes to calibration-log.md",
                    )
                )
    # A missing matrix file is already reported by the SIZE_BUDGETS pass.

    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Always-loaded rules hygiene: size budgets + matrix-row cap."
    )
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parents[2]),
        help="Repo root (default: two levels above this script).",
    )
    cli = parser.parse_args(argv)
    repo_root = Path(cli.root)

    violations = find_violations(repo_root)
    if not violations:
        n = len(SIZE_BUDGETS)
        print(
            f"rules-hygiene: OK ({n} budgeted files + matrix rows <= {MATRIX_ROW_MAX} chars)"
        )
        return 0

    print(f"rules-hygiene: {len(violations)} violation(s):")
    for v in violations:
        print(f"  [{v.kind}] {v.file}: {v.detail}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
